language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=ccl  # sporadic issues fetching files, just restart
    - LISP=clisp  # works on my systems ...
    #- LISP=cmucl # missing cim
    - LISP=ecl
    - LISP=sbcl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;  # XXX bad

script:
  - bin/run-tests
