language: lisp
sudo: required

env:
  global:
    - FAIL=no
  matrix:
    - LISP=sbcl
    - LISP=ecl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;  # XXX bad

script:
  - bin/run-tests
