language: lisp
sudo: required

env:
  matrix:
    - LISP=abcl
    - LISP=ccl
    - LISP=clisp
    - LISP=cmucl
    - LISP=ecl
    - LISP=sbcl

install:
  - curl https://raw.githubusercontent.com/luismbo/cl-travis/master/install.sh | sh;  # XXX bad

script:
  - bin/run-tests
